apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: kube-workshop
spec:
  containers:
    - name: myapp
      image: crccheck/hello-world
      ports:
        - name: api8000
          containerPort: 8000
      resources:
        requests:
          memory: 1Mi
          cpu: 0.5m
        limits:
          memory: 5Mi
          cpu: 1m
