apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-database-on-my-app
  namespace: kube-workshop
spec:
  template:
    metadata:
      name: migrate-database-on-my-app
    spec:
      restartPolicy: Never
      containers:
        - name: mytool-job
          image: ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/kube-workshop-app:YOURNAME
          command: ["yarn", "migrate-db"]
      imagePullSecrets:
        - name: bitbucket-secret
  backoffLimit: 4
