apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: kube-workshop
spec:
  # replicas: 1
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      labels:
        name: myapp
    spec:
      containers:
        - name: myapp
          image: crccheck/hello-world
          ports:
            - name: api8000
              containerPort: 8000
          resources:
            requests:
              memory: 1Mi
              cpu: 0.5m
            limits:
              memory: 10Mi
              cpu: 1m
