apiVersion: v1
kind: Pod
metadata:
  name: mytool
  namespace: kube-workshop
spec:
  containers:
    - name: mytool
      image: arunvelsriram/utils
      command: ["sleep", "1h"]
      resources:
        requests:
          memory: 1Mi
          cpu: 1m
        limits:
          memory: 10Mi
          cpu: 5m
